/*
 * glosario-data.js
 * Datos del Glosario de GuiaDev: términos y definiciones.
 * Cada entrada: { term, definition, theme }
 *  - term:        término o concepto
 *  - definition:  definición breve y clara en español
 *  - theme:       id de tema (ver GLOSSARY_THEMES)
 */
const GLOSSARY_THEMES = {
  fundamentos: { title: "Conceptos Fundamentales", icon: "fa-solid fa-lightbulb" },
  paradigmas:  { title: "Paradigmas de Programación", icon: "fa-solid fa-diagram-project" },
  oop:         { title: "Orientación a Objetos", icon: "fa-solid fa-cubes" },
  estructuras: { title: "Estructuras de Datos", icon: "fa-solid fa-database" },
  algoritmos:  { title: "Algoritmos y Complejidad", icon: "fa-solid fa-sitemap" },
  web:         { title: "Desarrollo Web", icon: "fa-solid fa-globe" },
  "bases-datos": { title: "Bases de Datos", icon: "fa-solid fa-table" },
  git:         { title: "Control de Versiones", icon: "fa-solid fa-code-branch" },
  concurrencia:{ title: "Concurrencia y Asincronía", icon: "fa-solid fa-clock" },
  testing:     { title: "Pruebas de Software", icon: "fa-solid fa-vial" },
  arquitectura:{ title: "Arquitectura y Diseño", icon: "fa-solid fa-building-columns" },
  redes:       { title: "Redes y Protocolos", icon: "fa-solid fa-network-wired" },
  devops:      { title: "DevOps y Despliegue", icon: "fa-solid fa-rocket" }
};

const GLOSSARY_DATA = [
  /* ---------------- Fundamentos ---------------- */
  { term: "Algoritmo", definition: "Secuencia finita y ordenada de pasos bien definidos que resuelven un problema o realizan una tarea concreta.", theme: "fundamentos" },
  { term: "Variable", definition: "Espacio de memoria con un nombre que almacena un valor que puede cambiar durante la ejecución del programa.", theme: "fundamentos" },
  { term: "Constante", definition: "Valor que no se puede modificar durante la ejecución del programa; su contenido permanece fijo.", theme: "fundamentos" },
  { term: "Dato", definition: "Información representable que un programa procesa, transporta o almacena, como números, texto o booleanos.", theme: "fundamentos" },
  { term: "Tipo de dato", definition: "Clasificación de un valor que define qué operaciones se pueden realizar sobre él y cuánto espacio ocupa (entero, flotante, cadena, etc.).", theme: "fundamentos" },
  { term: "Expresión", definition: "Combinación de valores, variables, operadores y llamadas que se evalúa para producir un resultado.", theme: "fundamentos" },
  { term: "Operador", definition: "Símbolo que realiza una operación sobre uno o más operandos, como suma (+), comparación (==) o lógica (&&).", theme: "fundamentos" },
  { term: "Condicional", definition: "Estructura de control que ejecuta un bloque de código solo si se cumple cierta condición (if, else).", theme: "fundamentos" },
  { term: "Bucle", definition: "Estructura de control que repite un bloque de código mientras se cumpla una condición o un número de veces (for, while).", theme: "fundamentos" },
  { term: "Iteración", definition: "Cada una de las repeticiones que un bucle realiza sobre un bloque de código.", theme: "fundamentos" },
  { term: "Función", definition: "Bloque de código reutilizable con un nombre que realiza una tarea específica y puede devolver un resultado.", theme: "fundamentos" },
  { term: "Parámetro", definition: "Variable declarada en la firma de una función que recibe un valor (el argumento) cuando se la invoca.", theme: "fundamentos" },
  { term: "Argumento", definition: "Valor concreto que se pasa a una función en el momento de llamarla para cubrir sus parámetros.", theme: "fundamentos" },
  { term: "Sintaxis", definition: "Conjunto de reglas que define cómo deben escribirse las instrucciones para que el compilador o intérprete las entienda.", theme: "fundamentos" },
  { term: "Semántica", definition: "Significado de las instrucciones del código: qué efecto tiene cada construcción, más allá de cómo esté escrita.", theme: "fundamentos" },
  { term: "Compilación", definition: "Proceso de traducir el código fuente de un lenguaje de alto nivel a código máquina ejecutable, de forma previa a la ejecución.", theme: "fundamentos" },
  { term: "Intérprete", definition: "Programa que ejecuta el código fuente línea por línea (o instrucción por instrucción) sin compilarlo antes.", theme: "fundamentos" },
  { term: "Compilador", definition: "Programa que traduce todo el código fuente de una vez a lenguaje máquina, generando un archivo ejecutable.", theme: "fundamentos" },
  { term: "Depuración (debug)", definition: "Proceso de identificar y corregir errores o comportamientos inesperados en el código.", theme: "fundamentos" },
  { term: "Bug", definition: "Error o defecto en el código que provoca un comportamiento incorrecto del programa.", theme: "fundamentos" },
  { term: "Error de sintaxis", definition: "Fallo que ocurre cuando el código no respeta las reglas gramaticales del lenguaje y no puede ser interpretado o compilado.", theme: "fundamentos" },
  { term: "Error de ejecución", definition: "Fallo que ocurre durante la ejecución del programa por condiciones no previstas, como dividir entre cero o acceder a un valor nulo.", theme: "fundamentos" },
  { term: "Error lógico", definition: "Fallo en el que el programa funciona pero produce resultados incorrectos por un error en la lógica del razonamiento.", theme: "fundamentos" },
  { term: "Comentario", definition: "Texto en el código que se usa para documentar y que es ignorado por el compilador o intérprete en la ejecución.", theme: "fundamentos" },
  { term: "Librería", definition: "Conjunto de funciones y recursos listos para reutilizar que se incorporan a un programa mediante importación.", theme: "fundamentos" },
  { term: "Framework", definition: "Entorno de trabajo que impone una estructura y ofrece herramientas para desarrollar aplicaciones de forma más rápida y organizada.", theme: "fundamentos" },
  { term: "API", definition: "Interfaz de programación de aplicaciones: conjunto de reglas y funciones que permiten que distintos programas se comuniquen entre sí.", theme: "fundamentos" },
  { term: "IDE", definition: "Entorno de Desarrollo Integrado: aplicación que agrupa editor de código, compilador, depurador y otras herramientas.", theme: "fundamentos" },
  { term: "Editor de código", definition: "Herramienta destinada a escribir y editar código fuente, con funciones como resaltado de sintaxis o autocompletado.", theme: "fundamentos" },
  { term: "CLI", definition: "Interfaz de Línea de Comandos: forma de interactuar con un programa o sistema escribiendo comandos de texto en una terminal.", theme: "fundamentos" },
  { term: "Pseudocódigo", definition: "Descripción de un algoritmo en lenguaje cercano al natural, sin reglas estrictas, útil para planificar antes de codificar.", theme: "fundamentos" },
  { term: "Recursión", definition: "Técnica en la que una función se llama a sí misma para resolver un problema dividiéndolo en casos más pequeños.", theme: "fundamentos" },
  { term: "Estado", definition: "Conjunto de valores que definen la situación de un programa o sistema en un momento determinado.", theme: "fundamentos" },
  { term: "Entrada y salida", definition: "Mecanismos por los que el programa recibe datos (entrada) y produce resultados (salida), como teclado, pantalla o archivos.", theme: "fundamentos" },
  { term: "Código fuente", definition: "Texto escrito en lenguaje de programación que, una vez compilado o interpretado, da lugar al programa ejecutable.", theme: "fundamentos" },
  { term: "Código máquina", definition: "Instrucciones en binario que el procesador ejecuta directamente, generadas por el compilador a partir del código fuente.", theme: "fundamentos" },

  /* ---------------- Paradigmas ---------------- */
  { term: "Paradigma de programación", definition: "Estilo o enfoque conceptual con el que se estructura y escribe el código para resolver problemas.", theme: "paradigmas" },
  { term: "Programación imperativa", definition: "Paradigma que describe el cómputo como una secuencia de instrucciones que modifican el estado paso a paso.", theme: "paradigmas" },
  { term: "Programación declarativa", definition: "Paradigma que describe qué se quiere obtener, dejando al sistema cómo lograrlo, sin detallar pasos.", theme: "paradigmas" },
  { term: "Programación estructurada", definition: "Estilo de programación basado en tres estructuras de control: secuencia, selección (if) e iteración (bucles).", theme: "paradigmas" },
  { term: "Programación funcional", definition: "Paradigma que trata el cómputo como la evaluación de funciones puras, evitando estado mutable y efectos secundarios.", theme: "paradigmas" },
  { term: "Función pura", definition: "Función que siempre devuelve el mismo resultado para los mismos argumentos y no produce efectos secundarios.", theme: "paradigmas" },
  { term: "Inmutabilidad", definition: "Propiedad de los datos de no poder cambiar después de ser creados; cualquier transformación crea un nuevo valor.", theme: "paradigmas" },
  { term: "Programación procedural", definition: "Paradigma imperativo que organiza el código en procedimientos o funciones que operan sobre datos.", theme: "paradigmas" },
  { term: "Programación lógica", definition: "Paradigma basado en hechos y reglas de lógica; el sistema deduce respuestas mediante un motor de inferencia (ej. Prolog).", theme: "paradigmas" },
  { term: "Programación concurrente", definition: "Paradigma que estructura el software en tareas que pueden ejecutarse de forma simultánea o intercalada.", theme: "paradigmas" },
  { term: "Lenguaje de alto nivel", definition: "Lenguaje cercano al humano y alejado de la máquina, con abstracciones que facilitan la programación.", theme: "paradigmas" },
  { term: "Lenguaje de bajo nivel", definition: "Lenguaje cercano al hardware, como el ensamblador, con poco nivel de abstracción y mayor control del sistema.", theme: "paradigmas" },
  { term: "Tipado estático", definition: "Sistema en el que el tipo de cada variable se conoce en tiempo de compilación, antes de ejecutar.", theme: "paradigmas" },
  { term: "Tipado dinámico", definition: "Sistema en el que el tipo de una variable se determina en tiempo de ejecución según el valor asignado.", theme: "paradigmas" },
  { term: "Tipado fuerte", definition: "Sistema que impide mezclar tipos incompatibles sin una conversión explícita, reduciendo errores.", theme: "paradigmas" },
  { term: "Tipado débil", definition: "Sistema que permite conversiones automáticas entre tipos incompatibles con mayor flexibilidad y riesgo de errores.", theme: "paradigmas" },
  { term: "Inferencia de tipos", definition: "Capacidad del compilador de deducir automáticamente el tipo de una variable a partir de su uso.", theme: "paradigmas" },
  { term: "Genericidad", definition: "Capacidad de escribir código (funciones o clases) que funcione con varios tipos de datos sin duplicarlos (genéricos).", theme: "paradigmas" },

  /* ---------------- POO ---------------- */
  { term: "Orientación a objetos (POO)", definition: "Paradigma que organiza el software en 'objetos' que combinan datos (atributos) y comportamientos (métodos).", theme: "oop" },
  { term: "Clase", definition: "Plantilla o modelo a partir del cual se crean objetos; define sus atributos y métodos.", theme: "oop" },
  { term: "Objeto", definition: "Instancia concreta de una clase, con su propio estado (valores de atributos) y comportamiento.", theme: "oop" },
  { term: "Instancia", definition: "Objeto concreto creado a partir de una clase mediante el operador de instanciación (new).", theme: "oop" },
  { term: "Atributo", definition: "Variable que pertenece a una clase u objeto y representa una característica o propiedad del mismo.", theme: "oop" },
  { term: "Método", definition: "Función que pertenece a una clase u objeto y define un comportamiento sobre sus atributos.", theme: "oop" },
  { term: "Constructor", definition: "Método especial que se ejecuta al crear un objeto para inicializar sus atributos.", theme: "oop" },
  { term: "Encapsulamiento", definition: "Principio que oculta el estado interno de un objeto y solo expone una interfaz controlada (públicos vs. privados).", theme: "oop" },
  { term: "Abstracción", definition: "Principio que reduce un objeto a sus características esenciales, ocultando detalles de implementación.", theme: "oop" },
  { term: "Herencia", definition: "Mecanismo por el que una clase hija reutiliza y extiende los atributos y métodos de una clase padre.", theme: "oop" },
  { term: "Clase padre", definition: "Clase base de la que otras clases heredan atributos y métodos; también llamada superclase.", theme: "oop" },
  { term: "Clase hija", definition: "Clase que hereda de otra y puede añadir o sobrescribir atributos y métodos; también llamada subclase.", theme: "oop" },
  { term: "Polimorfismo", definition: "Capacidad de que un mismo nombre o interfaz se comporte de forma distinta según el objeto que lo invoca.", theme: "oop" },
  { term: "Sobrecarga", definition: "Definición de varios métodos con el mismo nombre pero distinta firma (número o tipo de parámetros).", theme: "oop" },
  { term: "Sobrescritura", definition: "Reemplazo en una clase hija de la implementación de un método heredado de la clase padre.", theme: "oop" },
  { term: "Interfaz", definition: "Contrato que define qué métodos debe implementar una clase, sin especificar cómo, garantizando compatibilidad.", theme: "oop" },
  { term: "Clase abstracta", definition: "Clase que no se puede instanciar directamente y sirve de base para que otras clases hereden y completen sus métodos.", theme: "oop" },
  { term: "Modificador de acceso", definition: "Palabra clave que controla la visibilidad de un miembro: público, privado o protegido.", theme: "oop" },
  { term: "Público", definition: "Modificador de acceso que permite que un atributo o método sea accesible desde cualquier parte del programa.", theme: "oop" },
  { term: "Privado", definition: "Modificador de acceso que restringe el acceso a un atributo o método solo dentro de su propia clase.", theme: "oop" },
  { term: "Protegido", definition: "Modificador de acceso que permite el acceso a un miembro desde su clase y las clases que heredan de ella.", theme: "oop" },
  { term: "Composición", definition: "Relación en la que un objeto contiene a otro, que no puede existir sin el contenedor (relación fuerte).", theme: "oop" },
  { term: "Agregación", definition: "Relación en la que un objeto contiene a otros que pueden existir de forma independiente (relación débil).", theme: "oop" },
  { term: "Acoplamiento", definition: "Grado de dependencia entre clases o módulos; un acoplamiento bajo facilita el mantenimiento.", theme: "oop" },
  { term: "Cohesión", definition: "Grado en el que los elementos de una clase o módulo están relacionados; una cohesión alta es deseable.", theme: "oop" },
  { term: "Static (estático)", definition: "Miembro o método que pertenece a la clase y no a una instancia; se accede sin crear un objeto.", theme: "oop" },

  /* ---------------- Estructuras de datos ---------------- */
  { term: "Estructura de datos", definition: "Forma organizada de almacenar y gestionar datos para acceder y manipularlos de forma eficiente.", theme: "estructuras" },
  { term: "Array (arreglo)", definition: "Colección de elementos del mismo tipo almacenados en posiciones consecutivas y accesibles por índice.", theme: "estructuras" },
  { term: "Lista enlazada", definition: "Estructura de datos lineal en la que cada nodo almacena un valor y una referencia al siguiente nodo.", theme: "estructuras" },
  { term: "Pila (stack)", definition: "Estructura tipo LIFO (último en entrar, primero en salir) en la que solo se accede al último elemento añadido.", theme: "estructuras" },
  { term: "Cola (queue)", definition: "Estructura tipo FIFO (primero en entrar, primero en salir) similar a una fila de espera.", theme: "estructuras" },
  { term: "Deque", definition: "Cola de doble extremo que permite añadir y eliminar elementos tanto al inicio como al final.", theme: "estructuras" },
  { term: "Hash (tabla hash)", definition: "Estructura que asocia claves a valores y permite acceder a ellos en tiempo casi constante mediante una función hash.", theme: "estructuras" },
  { term: "Mapa (map)", definition: "Colección de pares clave-valor en la que cada clave es única y mapea a un valor (similar a un diccionario).", theme: "estructuras" },
  { term: "Diccionario", definition: "Estructura de datos que almacena pares clave-valor y permite búsquedas rápidas por la clave.", theme: "estructuras" },
  { term: "Conjunto (set)", definition: "Colección de elementos únicos sin orden (o con orden específico), útil para evitar duplicados.", theme: "estructuras" },
  { term: "Árbol", definition: "Estructura jerárquica con un nodo raíz y nodos hijos, donde cada nodo puede tener varios descendientes.", theme: "estructuras" },
  { term: "Grafo", definition: "Estructura formada por nodos (vértices) conectados por aristas, que modela relaciones entre elementos.", theme: "estructuras" },
  { term: "Nodo", definition: "Elemento básico de una estructura como árboles, grafos o listas; almacena un valor y referencias.", theme: "estructuras" },
  { term: "Heap", definition: "Árbol binario especial que mantiene el mayor (max-heap) o menor (min-heap) elemento accesible en la cima.", theme: "estructuras" },
  { term: "Complejidad temporal", definition: "Cantidad de tiempo que un algoritmo tarda en ejecutarse en función del tamaño de la entrada.", theme: "algoritmos" },
  { term: "Nodo raíz", definition: "El primer nodo de un árbol, desde el que se ramifican todos los demás; no tiene padre.", theme: "estructuras" },
  { term: "Hoja", definition: "Nodo de un árbol que no tiene hijos.", theme: "estructuras" },
  { term: "Índice", definition: "Posición numérica que identifica un elemento dentro de un array u otra estructura secuencial.", theme: "estructuras" },

  /* ---------------- Algoritmos ---------------- */
  { term: "Complejidad algorítmica", definition: "Medida de cómo crece el tiempo o el espacio que usa un algoritmo conforme crece el tamaño de la entrada.", theme: "algoritmos" },
  { term: "Notación Big O", definition: "Notación matemática que describe el peor caso de la complejidad de un algoritmo en función del tamaño de la entrada.", theme: "algoritmos" },
  { term: "Complejidad O(1)", definition: "Complejidad constante: el algoritmo tarda lo mismo sin importar el tamaño de la entrada.", theme: "algoritmos" },
  { term: "Complejidad O(n)", definition: "Complejidad lineal: el tiempo crece proporcionalmente al tamaño de la entrada n.", theme: "algoritmos" },
  { term: "Complejidad O(n²)", definition: "Complejidad cuadrática: el tiempo crece con el cuadrado de la entrada, típico de bucles anidados.", theme: "algoritmos" },
  { term: "Complejidad O(log n)", definition: "Complejidad logarítmica: el tiempo crece muy lentamente, típico de búsqueda binaria sobre datos ordenados.", theme: "algoritmos" },
  { term: "Complejidad O(n log n)", definition: "Complejidad lineal-logarítmica: típica de algoritmos de ordenamiento eficientes como mergesort o quicksort.", theme: "algoritmos" },
  { term: "Ordenamiento", definition: "Proceso de organizar los elementos de una colección según un criterio (numérico, alfabético, etc.).", theme: "algoritmos" },
  { term: "Búsqueda binaria", definition: "Algoritmo que encuentra un elemento en un array ordenado dividiendo repetidamente el intervalo por la mitad.", theme: "algoritmos" },
  { term: "Búsqueda lineal", definition: "Algoritmo que recorre los elementos uno a uno hasta encontrar el valor buscado.", theme: "algoritmos" },
  { term: "Ordenamiento por burbuja", definition: "Algoritmo simple que compara elementos adyacentes y los intercambia repetidamente; ineficiente para datos grandes.", theme: "algoritmos" },
  { term: "Dividir y conquistar", definition: "Técnica que divide el problema en subproblemas más pequeños, los resuelve y combina sus soluciones.", theme: "algoritmos" },
  { term: "Programación dinámica", definition: "Técnica que resuelve problemas complejos almacenando soluciones de subproblemas para reutilizarlas y evitar recalcular.", theme: "algoritmos" },
  { term: "Greedy (avaricioso)", definition: "Algoritmo que elige en cada paso la opción localmente óptima esperando llegar a una solución global óptima.", theme: "algoritmos" },
  { term: "Backtracking", definition: "Técnica de exploración que construye soluciones por pasos y retrocede cuando encuentra un camino inviable.", theme: "algoritmos" },
  { term: "Método de fuerza bruta", definition: "Estrategia que prueba todas las soluciones posibles sin optimización, correcta pero a menudo lenta.", theme: "algoritmos" },
  { term: "Heurística", definition: "Regla o método aproximado que encuentra soluciones buenas y rápidas, aunque no garantiza la óptima.", theme: "algoritmos" },

  /* ---------------- Web ---------------- */
  { term: "Frontend", definition: "Parte de una aplicación web con la que interactúa el usuario: estructura, presentación e interacción en el navegador.", theme: "web" },
  { term: "Backend", definition: "Parte de una aplicación que se ejecuta en el servidor y gestiona lógica, datos y reglas de negocio.", theme: "web" },
  { term: "Full-stack", definition: "Desarrollador o conjunto de capacidades que abarca tanto frontend como backend.", theme: "web" },
  { term: "HTML", definition: "Lenguaje de marcado que define la estructura y el contenido de una página web mediante etiquetas.", theme: "web" },
  { term: "CSS", definition: "Lenguaje de hojas de estilo que controla la presentación visual de los elementos HTML (colores, fuentes, layout).", theme: "web" },
  { term: "JavaScript", definition: "Lenguaje de programación que añade interactividad y dinamismo a las páginas web en el navegador.", theme: "web" },
  { term: "DOM", definition: "Modelo de Objetos del Documento: representación en árbol de una página que JavaScript puede modificar dinámicamente.", theme: "web" },
  { term: "SPA", definition: "Single Page Application: aplicación web que carga una sola página y actualiza el contenido dinámicamente sin recargar.", theme: "web" },
  { term: "Responsive design", definition: "Técnica para que una web se adapte y se vea correctamente en distintos tamaños de pantalla y dispositivos.", theme: "web" },
  { term: "Petición HTTP", definition: "Mensaje que un cliente envía a un servidor para solicitar un recurso o acción mediante verbos como GET o POST.", theme: "web" },
  { term: "HTTP", definition: "Protocolo de transferencia de hipertexto usado para la comunicación entre clientes y servidores web.", theme: "web" },
  { term: "HTTPS", definition: "Versión segura de HTTP que cifra la comunicación mediante TLS, protegiendo la información transmitida.", theme: "web" },
  { term: "Método GET", definition: "Verbo HTTP que solicita información de un recurso sin modificar el estado del servidor.", theme: "web" },
  { term: "Método POST", definition: "Verbo HTTP que envía datos al servidor para crear o procesar un recurso.", theme: "web" },
  { term: "JSON", definition: "Formato ligero de intercambio de datos basado en pares clave-valor, muy usado en APIs.", theme: "web" },
  { term: "API REST", definition: "Estilo de API web basado en recursos identificados por URL y operaciones HTTP, sin estado entre peticiones.", theme: "web" },
  { term: "Endpoint", definition: "URL específica de una API a la que se envían peticiones para acceder a un recurso o realizar una acción.", theme: "web" },
  { term: "Cookie", definition: "Pequeño dato que el servidor guarda en el navegador para recordar información entre peticiones o sesiones.", theme: "web" },
  { term: "Sesión", definition: "Período de interacción entre un usuario y una aplicación, manteniendo su estado a lo largo del tiempo.", theme: "web" },
  { term: "Cache", definition: "Almacenamiento temporal de datos o respuestas frecuentes para acelerar accesos posteriores.", theme: "web" },
  { term: "Middleware", definition: "Capa intermedia en el servidor que procesa las peticiones antes de la lógica final, como autenticación o logs.", theme: "web" },

  /* ---------------- Bases de datos ---------------- */
  { term: "Base de datos", definition: "Conjunto organizado de datos almacenados y gestionados de forma que permita su acceso, actualización y consulta.", theme: "bases-datos" },
  { term: "SQL", definition: "Lenguaje de consulta estructurado usado para crear, consultar y manipular bases de datos relacionales.", theme: "bases-datos" },
  { term: "Base de datos relacional", definition: "Tipo de base de datos que organiza la información en tablas relacionadas entre sí mediante claves.", theme: "bases-datos" },
  { term: "Base de datos NoSQL", definition: "Tipo de base de datos no relacional que almacena datos de formas flexibles como documentos, claves-valor o grafos.", theme: "bases-datos" },
  { term: "Tabla", definition: "Estructura de una base de datos relacional que organiza datos en filas y columnas.", theme: "bases-datos" },
  { term: "Registro", definition: "Fila de una tabla que representa un conjunto de valores de un mismo elemento o entidad.", theme: "bases-datos" },
  { term: "Campo", definition: "Columna de una tabla que almacena un atributo concreto de cada registro.", theme: "bases-datos" },
  { term: "Clave primaria", definition: "Campo o conjunto de campos que identifica de forma única cada registro de una tabla.", theme: "bases-datos" },
  { term: "Clave foránea", definition: "Campo que referencia la clave primaria de otra tabla para establecer una relación entre ambas.", theme: "bases-datos" },
  { term: "Índice de base de datos", definition: "Estructura que acelera la búsqueda y consulta de datos en una tabla a cambio de espacio y escritura extra.", theme: "bases-datos" },
  { term: "Consulta", definition: "Instrucción SQL (generalmente SELECT) que recupera datos de la base de datos según ciertos criterios.", theme: "bases-datos" },
  { term: "CRUD", definition: "Acrónimo de Create, Read, Update, Delete: las cuatro operaciones básicas sobre datos en un sistema.", theme: "bases-datos" },
  { term: "Transacción", definition: "Conjunto de operaciones sobre la base de datos que se ejecutan de forma atómica e indivisible.", theme: "bases-datos" },
  { term: "Normalización", definition: "Proceso de organizar tablas para reducir redundancia y evitar inconsistencias en los datos.", theme: "bases-datos" },
  { term: "Orfandad de datos", definition: "Registros que hacen referencia a otros que ya no existen, por falta de integridad referencial.", theme: "bases-datos" },

  /* ---------------- Git ---------------- */
  { term: "Control de versiones", definition: "Sistema que registra y gestiona los cambios en el código a lo largo del tiempo, permitiendo volver a versiones anteriores.", theme: "git" },
  { term: "Git", definition: "Sistema de control de versiones distribuido, el más utilizado, que guarda el historial de cambios del proyecto.", theme: "git" },
  { term: "Repositorio", definition: "Ubicación donde se almacenan el código y todo su historial de cambios de un proyecto.", theme: "git" },
  { term: "Commit", definition: "Registro de un conjunto de cambios realizados en el código, con un mensaje descriptivo y un identificador único.", theme: "git" },
  { term: "Rama (branch)", definition: "Línea de desarrollo independiente que permite trabajar en cambios sin afectar la rama principal.", theme: "git" },
  { term: "Rama principal", definition: "Rama principal de un repositorio (generalmente main o master) que contiene el código estable.", theme: "git" },
  { term: "Merge", definition: "Operación que integra los cambios de una rama en otra, combinando sus historiales.", theme: "git" },
  { term: "Rebase", definition: "Operación que reubica los commits de una rama sobre la punta de otra para un historial lineal.", theme: "git" },
  { term: "Pull request", definition: "Propuesta de integración de los cambios de una rama en otra, sujeta a revisión y discusión.", theme: "git" },
  { term: "Push", definition: "Comando que envía los commits locales a un repositorio remoto.", theme: "git" },
  { term: "Pull", definition: "Comando que trae los cambios de un repositorio remoto al entorno local.", theme: "git" },
  { term: "Clone", definition: "Comando que copia un repositorio remoto completo al entorno local.", theme: "git" },
  { term: "Fork", definition: "Copia independiente de un repositorio en otra cuenta, usada para desarrollar o contribuir sin afectar el original.", theme: "git" },
  { term: "Conflicto", definition: "Situación en la que dos cambios incompatibles afectan a la misma parte del código y deben resolverse manualmente.", theme: "git" },
  { term: "Staging (área de preparación)", definition: "Zona donde se marcan los cambios que se incluirán en el próximo commit.", theme: "git" },
  { term: "Gitignore", definition: "Archivo que lista los archivos o carpetas que Git debe ignorar y no versionar.", theme: "git" },

  /* ---------------- Concurrencia ---------------- */
  { term: "Concurrencia", definition: "Capacidad de ejecutar varias tareas de forma simultánea o intercalada, gestionando su coordinación.", theme: "concurrencia" },
  { term: "Paralelismo", definition: "Ejecución literal de varias tareas al mismo tiempo usando múltiples núcleos o procesadores.", theme: "concurrencia" },
  { term: "Hilo (thread)", definition: "Unidad mínima de ejecución dentro de un proceso; un proceso puede tener varios hilos.", theme: "concurrencia" },
  { term: "Proceso", definition: "Programa en ejecución con su propio espacio de memoria y contexto, gestionado por el sistema operativo.", theme: "concurrencia" },
  { term: "Asincronía", definition: "Modelo en el que una operación puede ejecutarse sin bloquear al programa, continuando con otras tareas mientras espera.", theme: "concurrencia" },
  { term: "Síncrono", definition: "Modelo en el que una operación bloquea la ejecución hasta que termina antes de continuar.", theme: "concurrencia" },
  { term: "Promise", definition: "Objeto que representa el resultado (éxito o fallo) de una operación asíncrona que aún no está disponible.", theme: "concurrencia" },
  { term: "Callback", definition: "Función que se pasa como argumento y se ejecuta cuando se completa una operación asíncrona.", theme: "concurrencia" },
  { term: "async/await", definition: "Sintaxis que simplifica el trabajo con promesas, escribiendo código asíncrono de forma más legible y secuencial.", theme: "concurrencia" },
  { term: "Carrera crítica (race condition)", definition: "Situación en la que el resultado depende del orden de ejecución de tareas concurrentes sobre datos compartidos.", theme: "concurrencia" },
  { term: "Bloqueo (lock)", definition: "Mecanismo de sincronización que impide que varios hilos accedan a un recurso compartido al mismo tiempo.", theme: "concurrencia" },
  { term: "Deadlock", definition: "Situación en la que dos o más procesos se bloquean mutuamente esperando recursos que el otro mantiene.", theme: "concurrencia" },
  { term: "Semáforo", definition: "Variable de sincronización que controla el número de accesos simultáneos a un recurso compartido.", theme: "concurrencia" },
  { term: "Mutex", definition: "Mecanismo de exclusión mutua que garantiza que solo un hilo acceda a un recurso a la vez.", theme: "concurrencia" },
  { term: "Modelo actor", definition: "Modelo de concurrencia en el que los actores (entidades independientes) se comunican mediante mensajes asíncronos.", theme: "concurrencia" },

  /* ---------------- Testing ---------------- */
  { term: "Prueba unitaria", definition: "Prueba que verifica el comportamiento de la unidad más pequeña de código (una función o método) de forma aislada.", theme: "testing" },
  { term: "Prueba de integración", definition: "Prueba que verifica que distintos módulos o componentes funcionan correctamente al interactuar entre sí.", theme: "testing" },
  { term: "Prueba de aceptación", definition: "Prueba que valida si el sistema cumple los requisitos y expectativas del cliente o usuario final.", theme: "testing" },
  { term: "Test end-to-end (E2E)", definition: "Prueba que recorre el flujo completo de la aplicación como lo haría un usuario real.", theme: "testing" },
  { term: "TDD", definition: "Desarrollo guiado por pruebas: escribir primero el test que falla y luego el código mínimo para que pase.", theme: "testing" },
  { term: "Cobertura de código", definition: "Métrica que indica el porcentaje de líneas o ramas del código que son ejecutadas por las pruebas.", theme: "testing" },
  { term: "Mock", definition: "Objeto simulado que imita el comportamiento de una dependencia real para aislar la unidad bajo prueba.", theme: "testing" },
  { term: "Stub", definition: "Implementación de respaldo que devuelve respuestas fijas para probar el código que depende de ella.", theme: "testing" },
  { term: "Assertion", definition: "Comprobación dentro de una prueba que verifica que un valor o condición sea el esperado.", theme: "testing" },
  { term: "Regresión", definition: "Error que reaparece en una parte del sistema que antes funcionaba, a causa de un cambio posterior.", theme: "testing" },
  { term: "Caso de prueba", definition: "Conjunto de entradas, condiciones y resultado esperado que definen una verificación concreta del software.", theme: "testing" },

  /* ---------------- Arquitectura y diseño ---------------- */
  { term: "Arquitectura de software", definition: "Estructura de alto nivel de un sistema: sus componentes, sus relaciones y los principios que guían su diseño.", theme: "arquitectura" },
  { term: "Patrón de diseño", definition: "Solución general y reutilizable para un problema recurrente de diseño de software.", theme: "arquitectura" },
  { term: "Singleton", definition: "Patrón que garantiza que una clase tenga una única instancia global y un punto de acceso a ella.", theme: "arquitectura" },
  { term: "Factory", definition: "Patrón que centraliza la creación de objetos delegando a subclases la decisión de qué clase instanciar.", theme: "arquitectura" },
  { term: "MVC", definition: "Modelo-Vista-Controlador: patrón que separa datos (modelo), interfaz (vista) y lógica de control (controlador).", theme: "arquitectura" },
  { term: "Arquitectura por capas", definition: "Organización del sistema en niveles (presentación, lógica, datos) donde cada capa usa los servicios de la inferior.", theme: "arquitectura" },
  { term: "Microservicios", definition: "Estilo arquitectónico que divide la aplicación en servicios pequeños, independientes y desplegables por separado.", theme: "arquitectura" },
  { term: "Arquitectura monolítica", definition: "Aplicación desarrollada como un único bloque donde todas las funcionalidades están unidas.", theme: "arquitectura" },
  { term: "Principio DRY", definition: "Don't Repeat Yourself: evitar la duplicación de código extrayendo lo común en componentes reutilizables.", theme: "arquitectura" },
  { term: "Principio KISS", definition: "Keep It Simple, Stupid: preferir soluciones simples en lugar de innecesariamente complejas.", theme: "arquitectura" },
  { term: "Principio YAGNI", definition: "You Aren't Gonna Need It: no añadir funcionalidad especulativa que no se va a usar en el futuro cercano.", theme: "arquitectura" },
  { term: "SOLID", definition: "Conjunto de cinco principios de diseño orientado a objetos que producen código más mantenible: SRP, OCP, LSP, ISP, DIP.", theme: "arquitectura" },
  { term: "Refactorización", definition: "Proceso de mejorar la estructura interna del código sin cambiar su comportamiento observable.", theme: "arquitectura" },
  { term: "Deuda técnica", definition: "Coste futuro de soluciones rápidas o mal diseñadas que se acumula y hace más difícil mantener el software.", theme: "arquitectura" },
  { term: "Smell (mal olor)", definition: "Indicio en el código de un posible problema de diseño que conviene refactorizar, aunque no sea un error funcional.", theme: "arquitectura" },

  /* ---------------- Redes ---------------- */
  { term: "IP", definition: "Protocolo de Internet que asigna direcciones únicas a los dispositivos para identificar su ubicación en la red.", theme: "redes" },
  { term: "Dirección IP", definition: "Número único que identifica a un dispositivo dentro de una red, como 192.168.1.1.", theme: "redes" },
  { term: "TCP", definition: "Protocolo de control de transmisión que garantiza la entrega ordenada y fiable de datos entre dispositivos.", theme: "redes" },
  { term: "UDP", definition: "Protocolo de datagramas que envía datos de forma rápida sin garantizar entrega ni orden, como en streaming o juegos.", theme: "redes" },
  { term: "Puerto", definition: "Número que identifica un servicio o aplicación concreto dentro de un dispositivo (ej. 80 para HTTP).", theme: "redes" },
  { term: "DNS", definition: "Sistema de nombres de dominio que traduce nombres legibles (www.ejemplo.com) a direcciones IP.", theme: "redes" },
  { term: "Cliente-servidor", definition: "Modelo en el que el cliente solicita recursos y el servidor los proporciona, respondiendo a las peticiones.", theme: "redes" },
  { term: "Socket", definition: "Extremo de una conexión de red que permite a dos programas comunicarse a través de una red.", theme: "redes" },
  { term: "Latencia", definition: "Tiempo que tarda un dato en viajar desde el origen hasta el destino en una red.", theme: "redes" },
  { term: "Bandwidth (ancho de banda)", definition: "Cantidad máxima de datos que puede transmitirse por una conexión en un intervalo de tiempo.", theme: "redes" },
  { term: "Firewall", definition: "Sistema de seguridad que filtra el tráfico de red permitiendo o bloqueando conexiones según reglas.", theme: "redes" },
  { term: "WebSocket", definition: "Protocolo que permite comunicación bidireccional y en tiempo real entre cliente y servidor.", theme: "redes" },

  /* ---------------- DevOps / despliegue ---------------- */
  { term: "DevOps", definition: "Cultura y conjunto de prácticas que integran desarrollo y operaciones para entregar software de forma continua.", theme: "devops" },
  { term: "CI (Integración Continua)", definition: "Práctica de integrar y probar el código de forma automática y frecuente al hacer commits.", theme: "devops" },
  { term: "CD (Entrega Continua)", definition: "Práctica de mantener el código siempre en un estado desplegable y publicarlo de forma automatizada.", theme: "devops" },
  { term: "Pipeline", definition: "Secuencia automatizada de pasos que lleva el código desde el commit hasta el despliegue.", theme: "devops" },
  { term: "Docker", definition: "Plataforma de contenedores que empaqueta una aplicación con sus dependencias para ejecutarla de forma consistente.", theme: "devops" },
  { term: "Contenedor", definition: "Unidad ligera y ejecutable que incluye el código y sus dependencias, aislada del sistema host.", theme: "devops" },
  { term: "Imagen", definition: "Plantilla inmutable que define el contenido de un contenedor; a partir de ella se crean contenedores.", theme: "devops" },
  { term: "Orquestación", definition: "Gestión automática del ciclo de vida de múltiples contenedores: despliegue, escalado y red.", theme: "devops" },
  { term: "Kubernetes", definition: "Sistema de orquestación de contenedores que automatiza el despliegue, escalado y gestión de aplicaciones.", theme: "devops" },
  { term: "Despliegue (deploy)", definition: "Proceso de poner en producción una versión de la aplicación para que sea accesible a los usuarios.", theme: "devops" },
  { term: "Rollback", definition: "Operación de volver a una versión anterior de la aplicación ante un fallo en el despliegue.", theme: "devops" },
  { term: "Escalabilidad", definition: "Capacidad del sistema de manejar un aumento de carga añadiendo recursos o instancias.", theme: "devops" },
  { term: "Cloud computing", definition: "Entrega de recursos de computación (servidores, almacenamiento, servicios) por internet bajo demanda.", theme: "devops" },
  { term: "Monitoreo", definition: "Supervisión continua del estado y rendimiento de la aplicación y la infraestructura.", theme: "devops" }
];
